services:
  db:
    image: postgres:13.3
    container_name: kanban-postgres
    restart: always
#    volumes:
#      - kanban-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
    ports:
      - 5432:5432  

  app:
    image: lessoncodeby/kanban:latest
    container_name: kanban-app
    restart: always
    environment:
      - DB_SERVER=kanban-postgres
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
    ports:
      - 8085:8080 
    depends_on:
      - db