apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        ports:
        - containerPort: 80
        env:
          - name: PGADMIN_DEFAULT_PASSWORD
            value: secrets123
          - name: PGADMIN_DEFAULT_EMAIL
            value: admin@admin.me
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: actions-runner-system
spec:
  type: NodePort
  ports:
    - port: 8061
      targetPort: 80
      nodePort: 30088 # This is the external port
  selector:
    app: pgadmin