apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: actions-runner-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: wrouesnel/postgres_exporter
          ports:
            - containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              value: "postgres://kanban:kanban@postgres.actions-runner-system.svc.cluster.local:5432/postgres?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: actions-runner-system
spec:
  type: NodePort
  ports:
    - port: 9187
      targetPort: 9187
      nodePort: 30087 # This is the external port
  selector:
    app: postgres-exporter