apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: actions-runner-system
spec:
  selector:
    app: prometheus-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 30089 # This is the external port
  type: NodePort