---
name: Java CI with Maven
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      DB_URL: 192.168.206.135
      DB_USER: kanban
      DB_PASS: kanban
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name: Make the script files executable
        run: chmod +x ./script/chvars.sh
      - name: Run the scripts
        run:
          ./script/chvars.sh
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: test
        run: pwd   
      - uses: actions/upload-artifact@v4
        with:
          name: kanban-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}.war
          path: ./target/Kanban.war
  docker-pub:
    runs-on: ubuntu-latest
    needs:
      - build-app
    strategy:
      matrix:
        include:
          - image: lessoncodeby/kanban
            dockerfile: Docker/Dockerfile
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: actions/download-artifact@v4
        with:
          name: kanban-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}.war
          path: ./ROOT.war
      - run: ls 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: v-${{ github.run_number }}, latest
          labels: ${{ steps.meta.outputs.labels }}
